version: '3.9'

services:
  django:
    image: django-docker
    build:
      context: .
      args:
        - SUPERUSER_USERNAME
        - SUPERUSER_PASSWORD
        - SUPERUSER_EMAIL
    ports:
      - "8000:8000"
    env_file:
      - .env